//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakServiceTest.CloudTakMoveService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudTakMoveService.ITakMoveService")]
    public interface ITakMoveService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITakMoveService/GetMove", ReplyAction="http://tempuri.org/ITakMoveService/GetMoveResponse")]
        string GetMove(string ptn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITakMoveService/GetMove", ReplyAction="http://tempuri.org/ITakMoveService/GetMoveResponse")]
        System.Threading.Tasks.Task<string> GetMoveAsync(string ptn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITakMoveServiceChannel : TakServiceTest.CloudTakMoveService.ITakMoveService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TakMoveServiceClient : System.ServiceModel.ClientBase<TakServiceTest.CloudTakMoveService.ITakMoveService>, TakServiceTest.CloudTakMoveService.ITakMoveService {
        
        public TakMoveServiceClient() {
        }
        
        public TakMoveServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TakMoveServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TakMoveServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TakMoveServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMove(string ptn) {
            return base.Channel.GetMove(ptn);
        }
        
        public System.Threading.Tasks.Task<string> GetMoveAsync(string ptn) {
            return base.Channel.GetMoveAsync(ptn);
        }
    }
}
